### ISSUE TITLE
Build error targeting Mac on OSX Lion with possible fix

### ISSUE THREAD

**Issue by bapuna** [underscorediscovery/flow#33]
After initial setup and successfully running:

```
haxelib run flow run web
```

I thought "Awesome! Now let's see how to compile to Mac...". So I tried:

```
haxelib run flow run mac
```

Which resulted in an error:

```
flow / 1.0.0-alpha.1
flow / target is mac ( arch 64 )

flow / project - searching project root /Volumes/DataHD/haxe/Libraries/snowkit/luxe/tests/features/draw
flow / project - using project file /Volumes/DataHD/haxe/Libraries/snowkit/luxe/tests/features/draw/project.flow
flow / build - luxe - test - draw 1.0.0 for mac
flow / build - running haxe ...
flow / build - running hxcpp ...
g++ -Iinclude -c -fvisibility=hidden -stdlib=libstdc++ -O2 -I/usr/lib/haxe/lib/hxcpp/3,1,39/include -DHX_MACOS -m64 -Wno-parentheses -Wno-unused-value -Wno-format-extra-args -DHXCPP_M64 -DHXCPP_VISIT_ALLOCS -DHXCPP_API_LEVEL=0 -frtti -x c++-header -o obj/darwin64//__pch/haxe/hxcpp.h.gch /usr/lib/haxe/lib/hxcpp/3,1,39/include/hxcpp.h
cc1plus: error: unrecognized command line option "-stdlib=libstdc++"
flow / 
 build - stopping because of errors in hxcpp compile
```

The main thing that seemed to mean anything to me was:

```
cc1plus: error: unrecognized command line option "-stdlib=libstdc++"
```

After some research https://github.com/HaxeFoundation/hxcpp/issues/32 I found that adding the following line somewhere between `<section id="vars">` and `</section>` in my **.hxcpp_config.xml** file located in my home directory fixed the problem:

```
<set name="HXCPP_GCC" value="1" />
```

After that, building for Mac worked fine.

Hopefully this was the right place to post about this issue even though it's really a hxcpp problem. I figure there might be someone like me out there not running the latest OSX and also unfamiliar with Haxe who might run into the same problem. Maybe this post will save them a little time and frustration :)

**Comment by chichilatte** [comment]
Thanks @bapuna, worked a treat!

**Comment by bapuna** [comment]
You're welcome! I'm glad to know it helped @chichilatte.
