### ISSUE TITLE
Dependencies with - or . in names

### ISSUE THREAD

**Issue by eliasku** [underscorediscovery/flow#37]
There is way to include packages like `greatlib.color` or `lib-tween` with `-` or `.` in names? BTW, github, haxelib and npm support that kind of names.

**Comment by underscorediscovery** [comment]
iirc this was already fixed along the way?

note [here](https://github.com/underscorediscovery/flow/blob/master/src/flow/util/haxelib.js#L41) is where the regex is parsing the names, you will see (and in the commit logs) that - and . were added because of libraries with these type of names earlier on.

Perhaps what you are seeing is not directly this?
Did you run with `log --4` and see if it has any info about what is happening exactly?

**Comment by eliasku** [comment]
```
flow / build - HorrorDemo 0.0.1 for web
flow / prepare - project HorrorDemo
flow / prepare - dependency tree ...
flow /    parsing dependencies for HorrorDemo
flow /         -    - found dependency horror * 
flow /         -    - found dependency snow * 
flow /        looking for dependency project file (maybe) at /Users/eliasku/Work/github/horror/horror.flow
flow / 
 syntax error in project file
 > /Users/eliasku/Work/github/horror/horror.flow:17:11 Expected ":" but "-" found. 
```


```
		build : {

			dependencies : {
				horror-debug : '*',
				horror-signals : '*',
				snow : '*',
				format : '*'
			},

			defines : ['hrr_snow', 'hrr_gl', 'hrr_glsl']
		}
	},
```

**Comment by eliasku** [comment]
If I use "horror-debug" as property, I get 
```/Users/eliasku/Work/github/horror/src/horror/render/Texture.hx:5: characters 7-19 : Class not found : horror.Debug```

but in logs it seems right added to hxml:
```
-cp /Users/eliasku/Work/github/horror/
-cp /Users/eliasku/Work/github/horror/src/
-cp /usr/lib/haxe/lib/snow/git/
-cp /Users/eliasku/Work/github/horror-debug/
-cp /Users/eliasku/Work/github/horror-signals/
-cp /usr/lib/haxe/lib/format/3,1,2/
```

**Comment by underscorediscovery** [comment]
Right yea, for the .flow file common logic of a "property" key (say like in js) would need a `" "` if you had invalid alphanumeric in the name. For property nodes that have those, you must enclose them in quotes as you found. You can't escape that right now.

I looked at the horror-debug repo, it has a /src folder in it.
`-cp /Users/eliasku/Work/github/horror-debug/` != `-cp /Users/eliasku/Work/github/horror-debug/src`

**Comment by eliasku** [comment]
oh, sorry, seems like I need to include `include.flow` and specify `sourcepath` for every external module... BTW why don't scan haxelib.json for "classPath" : "src" ?

**Comment by underscorediscovery** [comment]
I don't see that documented anywhere, can you link to where it's a feature?

**Comment by underscorediscovery** [comment]
Btw I should also note that the flow _user_ of a dependency can specify the codepaths for it, I forgot that this was added. The rule is that a `dependency` can be a string or an object, if the object has a codepaths value they will be added to the list.

```
dependencies : {
    horror-debug : {
        version:'*',
        codepaths: ['src', 'other']
    },
    horror-signals : '*',
    snow : '*',
    format : '*'
},
```

**Comment by underscorediscovery** [comment]
Since this discussion is no longer related to the original issue (and the issue was a mislead) we can close this, but you can continue to report back if you have other findings/problems.

**Comment by eliasku** [comment]
Works! Nice feature.

I think haxelib.json is just missing `classPath` from manual, many libraries are using that feature.

Now all works, but I detect strange codepaths duplicates. From flow build with log option:
```
-cp /Users/eliasku/Work/github/horror/
-cp /Users/eliasku/Work/github/horror/src/
-cp /Users/eliasku/Work/github/horror-debug/
-cp /Users/eliasku/Work/github/horror-debug/src/
-cp /Users/eliasku/Work/github/horror-signals/
-cp /Users/eliasku/Work/github/horror-signals/src/
``` 

Settings (or also available in my repos):
```
dependencies : {
				"horror-debug" : {
					version : '*',
					codepaths : ['src']
				},
				"horror-signals" : {
					version : '*',
					codepaths : ['src']
				},
				snow : '*',
				format : '*'
```

No ideas why it has been duplicated, but all works now. Thanks one more time

**Comment by underscorediscovery** [comment]
Yes, by default it will place the root of the haxelib in the class path plus any additional codepaths you specify.

What I want to do is, provided haxelib feature is official for classPath : 

- try flow codepaths as normal
- if not flow file try haxelib `codePath`
- if not found use root/

This would be a simple change, but I would rather be certain that the classPath is in fact a feature of haxelib official before it gets removed next release and people come to rely on it.

**Comment by eliasku** [comment]
It will be great!
I've created the issue https://github.com/HaxeFoundation/HaxeManual/issues/78 to update the documentation or get explanations why classPath has not documented yet
