### ISSUE TITLE
Build dependency libraries can't be included if they have a "-" in their name.

### ISSUE THREAD

**Issue by FuzzyWuzzie** [underscorediscovery/flow#45]
For example:

```
build : {
  dependencies : {
    luxe : '*',
    polygonal-ds : '*'
  }
}
```

Fails with:
```
 > syntax error in project file
 > project.flow:27:18 Expected ":" but "-" found. 
```

**Comment by anissen** [comment]
`polygonal-ds` should be in quotes. Try the following instead:

```json
build : {
  dependencies : {
    luxe : '*',
    'polygonal-ds' : '*'
  }
}
```

**Comment by FuzzyWuzzie** [comment]
Ahh, good to know. Thanks!

**Comment by underscorediscovery** [comment]
As with any stream based parser it's a bit more complex to know what your intention was, it only sees what is right there, not the state overall. Deducing when you put invalid characters in a key like that will require some special logic outside of the parser part, which is probably easier.

There's a good chance that flow will get a large amount of rewriting done before everything else reaches beta, so we'll try to address these type of things when we do.
