### ISSUE TITLE
Keep web server running, only recompile

### ISSUE THREAD

**Issue by oxysoft** [underscorediscovery/flow#55]
Hi, currently I have to run 'haxelib run flow run web' (actually ctrl+b in sublime text for me) every time I want to test my new code and this web server stops after 10 seconds of not getting any requests. Is it possible to keep it running and only have the code recompile? This way, I could simply refresh the page once it's ready

Thanks

**Comment by underscorediscovery** [comment]
Yes, it is easily possible.

`haxelib run flow run --timeout 0`

And from the flow status menu in sublime text, choose "toggle build only".

You can also set up livereload, which I updated the tutorial on just now.

http://snowkit.org/2015/01/26/web-livereload-example/

**Comment by oxysoft** [comment]
Hey thanks, this is exactly what I was looking and it really seals the deal: I will definitely use Luxe for this Ludum Dare!

**Comment by underscorediscovery** [comment]
Be sure to join the http://snowkit.org/chat for more hands on help :)
