### ISSUE TITLE
doc/example of haxe, hxcpp flags getting through flow

### ISSUE THREAD

**Issue by raould** [underscorediscovery/flow#56]
hi, I'm trying to follow http://gamehaxe.com/2012/09/14/hxcpp-built-in-debugging/ to profile. It is not at all clear to me how to get the flags e.g. HXCPP_STACK_TRACE to go from my project.flow file through the Haxe compiler, and also to HXCPP successfully. I am trying
```
  build : {
            flags: [ '-D HXCPP_DEBUG_LINK', '-D DHXCPP_STACK_TRACE', '-D HXCPP_STACK_LINE' ],
            dependencies : {
                luxe : '*',
            }
        },
```
but when I run with --log 5 I can see those in some places, but not in each line of cpp compliation.

```
$ grep -n STACK_TRACE /tmp/l2
296:  DHXCPP_STACK_TRACE: 
297:   { name: 'DHXCPP_STACK_TRACE',
417:-D DHXCPP_STACK_TRACE
609:-D DHXCPP_STACK_TRACE
757:flow / build - cpp - Options.txt contents: DHXCPP_STACK_TRACE=1 HXCPP_DEBUG_LINK=1 HXCPP_STACK_LINE=1 arch-32=1 arch_32=1 desktop=1 haxe3=1 haxe_ver=3.2 hxcpp=1 hxcpp_api_level=321 hxcpp_static_std=1 linux=1 luxe=1 luxe_native=1 no-compilation=1 no_compilation=1 parcel_thread_disabled=1 snow=1 snow_dynamic_link=1 snow_module_audio_openal=1 snow_module_input_sdl=1 snow_module_windowing_sdl=1 snow_native=1 hxcpp=/usr/lib/haxe/lib/hxcpp/3,2,102/
```

**Comment by underscorediscovery** [comment]
First, `flags` are `haxe` compiler flags.
What you are trying to add are `defines`, 

`defines: ['HXCPP_DEBUG_LINK', 'DHXCPP_STACK_TRACE', 'HXCPP_STACK_LINE']`

Second, 
You don't need to do this manually.
Define `profiler` (say with `flow build --d profiler` or `defines:['profiler']`) and **press and hold** ctrl p. When you let go a file will be saved in the cwd with the profile dump. The console logs this information (press the key under escape, and press 1 to cycle debug views).

You might also be interested in trying hxScout. 
See http://snowkit.org/2015/07/31/using-hxscout-with-snowluxe/

And finally, read the dev logs and take note that performance is important, but finishing the engine is more of a priority than chasing rabbit holes. I would advise you not worry about performance during the alpha, as it is a constant work in progress.
