### ISSUE TITLE
Flow doesn't override mobile options.

### ISSUE THREAD

**Issue by darmie** [underscorediscovery/flow#69]
I set flow project file to set fullscreen as false, and landscape to only portrait. It didn't work. 

```
...
    app : {
      name : 'frejo_test',
      package : 'com.frejo.test',
      mobile: {
        fullscreen: false,
        orientation: 'portrait'
      }
    },
...
```

**Comment by ruby0x1** [comment]
mobile options are not used any more (these were deprecated, the documentation is just sorely outdated). 

The approach taken for each mobile platform is to follow the platform paradigms 1:1, i.e you get an xcode project, you set the orientation and icons and everything in xcode, the native tool for the platform. Same for android and android studio, this is the only possible way to give access to those platforms in a way that is forward compatible and never prevents the user from using the platform features directly.
